"""empty message

Revision ID: 1d33bc215e3e
Revises:
Create Date: 2026-09-14 19:36:38.316159

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1d33bc215e3e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "area",
        sa.Column("hh_area_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("hh_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_area")),
        sa.UniqueConstraint("hh_area_id", name=op.f("uq_area_hh_area_id")),
    )
    op.create_table(
        "employer",
        sa.Column("hh_employer_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("hh_url", sa.Text(), nullable=True),
        sa.Column("hh_alternate_url", sa.Text(), nullable=True),
        sa.Column(
            "logo_urls",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employer")),
        sa.UniqueConstraint(
            "hh_employer_id", name=op.f("uq_employer_hh_employer_id")
        ),
    )
    op.create_table(
        "metro",
        sa.Column("hh_metro_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("hh_order", sa.Integer(), nullable=True),
        sa.Column(
            "line",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metro")),
        sa.UniqueConstraint("hh_metro_id", name=op.f("uq_metro_hh_metro_id")),
    )
    op.create_table(
        "owner",
        sa.Column("hh_owner_id", sa.String(length=32), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("middle_name", sa.Text(), nullable=True),
        sa.Column("age", sa.SmallInteger(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum(
                "male",
                "female",
                name="gender",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column(
            "contact",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owner")),
        sa.UniqueConstraint("hh_owner_id", name=op.f("uq_owner_hh_owner_id")),
    )
    op.create_table(
        "resume",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resume_type",
            sa.Enum(
                "short",
                "full",
                name="resume_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("s3_bucket", sa.String(length=63), nullable=False),
        sa.Column("s3_key", sa.String(length=1024), nullable=False),
        sa.Column("s3_version_id", sa.String(length=1024), nullable=True),
        sa.Column("hh_resume_id", sa.String(length=64), nullable=False),
        sa.Column("hh_real_id", sa.String(length=32), nullable=True),
        sa.Column("hh_url", sa.Text(), nullable=True),
        sa.Column("hh_alternate_url", sa.Text(), nullable=True),
        sa.Column("hh_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hh_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("platform_id", sa.String(length=32), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "salary_amount", sa.Numeric(precision=14, scale=2), nullable=True
        ),
        sa.Column("salary_currency", sa.String(length=8), nullable=True),
        sa.Column("total_experience_months", sa.Integer(), nullable=True),
        sa.Column("skill_set", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("skills", sa.Text(), nullable=True),
        sa.Column(
            "photo",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("area_id", sa.Uuid(), nullable=True),
        sa.Column("metro_id", sa.Uuid(), nullable=True),
        sa.Column(
            "education_level",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "job_search_status",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "business_trip_readiness",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "travel_time",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "resume_locale",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "relocation_type",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "relocation_area",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "relocation_district",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "employments",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "schedules",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "employment_form",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "work_format",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "professional_roles",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "citizenship",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "work_ticket",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "language",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "portfolio",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "certificate",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "site",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "recommendation",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "hidden_fields",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "driver_license_types",
            sa.ARRAY(
                sa.Enum(
                    "A",
                    "B",
                    "C",
                    "D",
                    "E",
                    "BE",
                    "CE",
                    "DE",
                    "TM",
                    "TB",
                    name="driver_license_type",
                    native_enum=False,
                )
            ),
            nullable=True,
        ),
        sa.Column("has_vehicle", sa.Boolean(), nullable=True),
        sa.Column("has_medical_book", sa.Boolean(), nullable=True),
        sa.Column("has_self_employment", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["area.id"], name=op.f("fk_resume_area_id_area")
        ),
        sa.ForeignKeyConstraint(
            ["metro_id"], ["metro.id"], name=op.f("fk_resume_metro_id_metro")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["owner.id"], name=op.f("fk_resume_owner_id_owner")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume")),
        sa.UniqueConstraint(
            "s3_bucket",
            "s3_key",
            "s3_version_id",
            name=op.f("uq_resume_s3_bucket_s3_key_s3_version_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_resume_area_id"), "resume", ["area_id"], unique=False
    )
    op.create_index(
        op.f("ix_resume_hh_resume_id"),
        "resume",
        ["hh_resume_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resume_metro_id"), "resume", ["metro_id"], unique=False
    )
    op.create_index(
        "ix_resume_owner_history",
        "resume",
        [
            "owner_id",
            sa.literal_column("downloaded_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_table(
        "education",
        sa.Column("resume_id", sa.Uuid(), nullable=False),
        sa.Column("hh_education_id", sa.String(length=32), nullable=True),
        sa.Column(
            "education_type",
            sa.Enum(
                "primary",
                "additional",
                "attestation",
                "elementary",
                name="education_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "education_level",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("organization", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("year", sa.SmallInteger(), nullable=True),
        sa.Column("university_acronym", sa.Text(), nullable=True),
        sa.Column("hh_name_id", sa.String(length=32), nullable=True),
        sa.Column("hh_organization_id", sa.String(length=32), nullable=True),
        sa.Column("hh_result_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resume.id"],
            name=op.f("fk_education_resume_id_resume"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_education")),
    )
    op.create_index(
        op.f("ix_education_resume_id"),
        "education",
        ["resume_id"],
        unique=False,
    )
    op.create_table(
        "experience",
        sa.Column("resume_id", sa.Uuid(), nullable=False),
        sa.Column("hh_experience_id", sa.String(length=32), nullable=True),
        sa.Column("company", sa.Text(), nullable=True),
        sa.Column("hh_company_id", sa.String(length=32), nullable=True),
        sa.Column("company_url", sa.Text(), nullable=True),
        sa.Column("employer_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("area_id", sa.Uuid(), nullable=True),
        sa.Column(
            "industry",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "industries",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["area.id"], name=op.f("fk_experience_area_id_area")
        ),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employer.id"],
            name=op.f("fk_experience_employer_id_employer"),
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resume.id"],
            name=op.f("fk_experience_resume_id_resume"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experience")),
    )
    op.create_index(
        op.f("ix_experience_area_id"), "experience", ["area_id"], unique=False
    )
    op.create_index(
        op.f("ix_experience_employer_id"),
        "experience",
        ["employer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experience_resume_id"),
        "experience",
        ["resume_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_experience_resume_id"), table_name="experience")
    op.drop_index(op.f("ix_experience_employer_id"), table_name="experience")
    op.drop_index(op.f("ix_experience_area_id"), table_name="experience")
    op.drop_table("experience")
    op.drop_index(op.f("ix_education_resume_id"), table_name="education")
    op.drop_table("education")
    op.drop_index("ix_resume_owner_history", table_name="resume")
    op.drop_index(op.f("ix_resume_metro_id"), table_name="resume")
    op.drop_index(op.f("ix_resume_hh_resume_id"), table_name="resume")
    op.drop_index(op.f("ix_resume_area_id"), table_name="resume")
    op.drop_table("resume")
    op.drop_table("owner")
    op.drop_table("metro")
    op.drop_table("employer")
    op.drop_table("area")
    # ### end Alembic commands ###
