from collections.abc import Iterator

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, TextClause, text

from css_models import Base

EXPECTED = {table.name for table in Base.metadata.sorted_tables}

TABLES = text("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
""")

CONSTRAINTS = text("""
    SELECT conname
    FROM pg_constraint
    JOIN pg_class ON pg_class.oid = pg_constraint.conrelid
    JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
    WHERE pg_namespace.nspname = 'public'
""")

INDEXES = text("""
    SELECT indexname
    FROM pg_indexes
    WHERE schemaname = 'public'
""")

TYPES = text("""
    SELECT typname
    FROM pg_type
    JOIN pg_namespace ON pg_namespace.oid = pg_type.typnamespace
    WHERE pg_namespace.nspname = 'public' AND typtype = 'e'
""")


@pytest.fixture
def at_head(alembic_config: Config, schema: Engine) -> Iterator[Config]:
    """Let a test move the schema around and put it back afterwards."""
    try:
        yield alembic_config
    finally:
        command.upgrade(config=alembic_config, revision="head")


def _names(engine: Engine, query: TextClause) -> set[str]:
    with engine.connect() as connection:
        return {row[0] for row in connection.execute(query)}


def test_there_is_a_single_head(alembic_config: Config) -> None:
    """Two heads mean two branches and an upgrade that picks one at random."""
    scripts = ScriptDirectory.from_config(alembic_config)

    assert len(scripts.get_heads()) == 1


def test_upgrade_creates_every_table(schema: Engine) -> None:
    """The migrations build exactly the tables the models declare."""
    created = _names(schema, TABLES)

    assert created == EXPECTED | {"alembic_version"}


def test_models_match_the_migrations(schema: Engine, at_head: Config) -> None:
    """Catches a model changed without regenerating a migration."""
    try:
        command.check(config=at_head)
    except AutogenerateDiffsDetected as drift:
        pytest.fail(f"run `make migrations.local.generate`: {drift}")


def test_enums_did_not_become_postgres_types(schema: Engine) -> None:
    """A native enum type would make adding an HH option a migration."""
    assert _names(schema, TYPES) == set()


def test_constraint_names_survive_into_the_database(schema: Engine) -> None:
    """Names are what a future migration uses to drop or alter a rule."""
    names = _names(schema, CONSTRAINTS)
    ours = {name for name in names if not name.startswith("alembic")}

    assert ours
    assert all(
        name.startswith(("pk_", "fk_", "uq_", "ck_")) for name in ours
    ), sorted(name for name in ours if not name.startswith("ck_"))


def test_the_s3_constraint_ignores_null_versions(schema: Engine) -> None:
    """NULLS NOT DISTINCT is the part that closes the duplicate hole."""
    query = text("""
        SELECT pg_get_constraintdef(oid)
        FROM pg_constraint
        WHERE conname = 'uq_resume_s3_bucket_s3_key_s3_version_id'
    """)

    with schema.connect() as connection:
        definition = connection.execute(query).scalar_one()

    assert "NULLS NOT DISTINCT" in definition


def test_downgrade_leaves_nothing_behind(
    schema: Engine, at_head: Config
) -> None:
    """A half-cleaned database blocks the next upgrade with a name clash."""
    command.downgrade(config=at_head, revision="base")

    assert _names(schema, TABLES) == {"alembic_version"}
    assert _names(schema, INDEXES) == {"alembic_version_pkc"}
    assert _names(schema, TYPES) == set()


def test_downgrade_and_upgrade_rebuild_the_same_schema(
    schema: Engine, at_head: Config
) -> None:
    """Rolling back and forward must land on the schema we started from."""
    before = _names(schema, TABLES) | _names(schema, INDEXES)

    command.downgrade(config=at_head, revision="base")
    command.upgrade(config=at_head, revision="head")

    assert _names(schema, TABLES) | _names(schema, INDEXES) == before


def test_upgrading_twice_changes_nothing(
    schema: Engine, at_head: Config
) -> None:
    """The Lambda is invoked again on every deploy and must stay quiet."""
    command.upgrade(config=at_head, revision="head")

    assert _names(schema, TABLES) == EXPECTED | {"alembic_version"}
